--- 
title: "Proyecto Migración"
author: "Equipo Investigación"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---
# Fuentes de datos en el triangulo del norte de Centroamérica sobre migración, ocupación y empleo


## El Salvador

### Transparencia

El Salvador cuenta con un instituto especializado en migración que publica datos sobre este tema: la Dirección General de Migración y Extranjería de El Salvador (DGME). El apartado de estadísticas del sitio oficial no tiene ningún contenido. Al parecer, los datos se encuentran en el sitio de Transparencia del gobierno. Se recomienda hacer uso de los filtros o el buscador para optimizar las búsquedas.

https://www.transparencia.gob.sv/institutions/dgme/documents/estadisticas
https://www.migracion.gob.sv/estadisticas/
https://www.transparencia.gob.sv/institutions/dgme/documents/estadisticas

Contiene información sobre salvadoreños retornados por país, salidas migratorias por diferentes puestos de manera anual.


### Dirección General de Estadística y Censos de El Salvador

La DIGESTYC es una institución estatal de El Salvador encargada de la elaboración de estudios estadístico. Esta oficina pública depende del Ministerio de Economía. El sitio de la Dirección General de Estadísticas y Censos de El Salvador tiene información sobre estadísticas económicas, sociales, cartografía social y actualización de datos sobre el país. 

En el sitio oficial de DIGESTYC podemos encontrar distintos apartados: Institución, servicio, temas, novedades, etc. En el apartado de “Temas” se divide en subtemas que incluyen: estadísticas económicas, sociales, cartografía censal, etc. Dentro de las Estadísticas Sociales, se encuentran el Censo de Población y Vivienda y proyecciones. 

http://www.digestyc.gob.sv/index.php/temas/des/poblacion-y-estadisticas-demograficas.html
https://www.transparencia.gob.sv/institutions/minec/documents/estadisticas
http://www.digestyc.gob.sv/index.php/temas/des/poblacion-y-estadisticas-demograficas/censo-de-poblacion-y-vivienda.html
http://www.digestyc.gob.sv/index.php/temas/des/poblacion-y-estadisticas-demograficas/censo-de-poblacion-y-vivienda/publicaciones-censos.html
http://www.digestyc.gob.sv/index.php/temas/des/poblacion-y-estadisticas-demograficas/censo-de-poblacion-y-vivienda/poblacion-censos.html


En los links anteriores se encuentra todo lo relacionado a: 

+ Censos: Población, edificios y vivienda, Agropecuario e Industrial y Comercial

+ Estadísticas continuas: Geográficas y Meteorológicas, Demográficas y de Salud Pública, Educacionales y Culturales, de Trabajo y Previsión social, Judiciales y Políticas, de Construcciones, Transporte y Vías de Comunicación, Agropecuarias, Industriales, de Comercio Exterior e Interior, Financieras, Fiscales y Administrativas, de Ingreso Nacional y Costo de Vida




### EHPM del DIGESTYC

+ Situación socioeconómica de los Hogares Salvadoreño
+ Cada 5 años

### Censo del DIGESTYC

+ Características de la Vivienda

+ Características del Hogar

+ Características de las Personas que Conforman el Hogar

+ Mortalidad y Emigración

+ Datos de las Personas del Hogar.

### Observatorio de estadística de género del DIGESTYC

+ Información sobre uso de tiempo

+ Género y migración

http://aplicaciones.digestyc.gob.sv/observatorio.genero/migraciones/index.aspx

### Otros


Además, existen distintos programas, principalmente internacionales o regionales, que publican una gran cantidad de los datos sobre migración. La mayoría de los programas son gestionados por organizaciones internacionales o instituciones nacionales, particularmente de estadística. La mayoría son encuestas sobre Demografía u Hogares. En El Salvador existen los siguientes: 


DTM Matriz de Seguimiento de Desplazamiento. Es un sistema informativo de la Organización Internacional. Esta matriz es una herramienta de la Organización Internacional para las Migraciones que brinda información estadística que didáctica para mejorar la comprensión sobre características y necesidades de grupos inmersos en dinámicas de movilidad. Herramienta clave para la recopilación de datos primarios y la elaboración de informes sobre movilidad humana, tanto a escala nacional regional y global. 

https://dtm.iom.int/el-salvador

https://mic.iom.int/webntmi/descargas/sv/2017/OIM-DTMsv.pdf
https://displacement.iom.int/sites/default/files/public/DOE%20Infosheet%20-%20201911_SP.pdf

https://reliefweb.int/report/el-salvador/dtm-el-salvador-flow-monitoring-survey-profiles-and-humanitarian-needs-migrants


Encuesta de Hogares de Propósitos Múltiples: Realizada por el Ministerio de Economía, a través de la Dirección General de Estadística y Censos (DIGESTYC).
La EHPM es un instrumento estadístico con el que cuenta el país, para proporcionar información sobre la situación socioeconómica de los Hogares salvadoreños. 


http://www.digestyc.gob.sv/index.php/temas/des/ehpm.html

http://www.digestyc.gob.sv/index.php/novedades/avisos/965-ya-se-encuentra-disponible-la-encuesta-de-hogares-de-propositos-multiples-2019.html


Iniciativa de Gestión de Información de Movilidad Humana en el Triángulo Norte. La OIM puso en marcha un proyecto financiado por la USAID denominado Iniciativa de Gestión de Información de Movilidad Humana en el Triángulo Norte (NTMI por sus siglas en inglés), cuyo objetivo es fortalecer las capacidades de los gobiernos de El Salvador, Guatemala y Honduras para recolectar, analizar y compartir información sobre la movilidad humana, con el fin de apoyar la acción humanitaria y proteger a las poblaciones vulnerables en los tres países.

https://mic.iom.int/webntmi/
https://mic.iom.int/webntmi/el-salvador/


Sistema Integrado de Gestión Migratoria. Al googlearlo no se encuentra un sitio oficial ni bases de datos. Lo más relevante relacionado es un Plan Anual Operativo de 2017 del Ministerio de Justicia y Seguridad Pública del gobierno de El Salvador. Este se descarga. 




## Honduras

### Instituto Nacional de Estadística 

El INE en Honduras tiene información sobre estadísticas económicas, sociales, cartografía censal y actualización de datos sobre el país. 

+ Estadísticas https://www.ine.gob.hn/V3/

+ Censos de Población y Vivienda https://www.ine.gob.hn/V3/censo-de-poblacion-y-vivienda/ En este se incluye 1. Características de la población, 2. Características Generales de la Vivienda 3. Mortalidad y Fecundidad, 4. Migración, 5. Género, 6. Grupos Poblacionales, 7. Mercado Laboral 8. Características económicas de la población interrelacionadas y proyecciones. 

+ Censo Migración https://www.ine.gob.hn/publicaciones/Censos/Censo_2013/04Tomo-IV-Migracion/index%20Censo.html

+ Censo Nacional de Ocupaciones de Honduras https://www.ine.gob.hn/V3/2019/07/04/clasificador-nacional-ocupaciones/

+ Migración y remesas. https://www.ine.gob.hn/V3/2019/05/14/migracion-y-remesas/ 

### Otros

Además, existen distintos programas, principalmente internacionales o regionales, que publican una gran cantidad de los datos sobre migración. La mayoría de los programas son gestionados por organizaciones internacionales o instituciones nacionales, particularmente de estadística. La mayoría son encuestas sobre Demografía u Hogares. En Honduras existen los siguientes:

+ DTM Matriz de Seguimiento de Desplazamiento

https://dtm.iom.int/honduras

+ Reporte Caravana 2021 – 6 flujos de personas migrantes en tránsito https://reliefweb.int/report/honduras/dtm-caravana-2021-reporte-situacional-6-de-flujos-de-personas-migrantes-en-tr-nsito

+ Iniciativa de Gestión de Información de Movilidad Humana en el Triángulo Norte

https://mic.iom.int/webntmi/honduras/

+ Sistema Integral de Atención al Migrante Retornado (SIAMIR)

## Guatemala


### Instituto Nacional de Estadística

El INE en Guatemala es el organismo oficial que presta los servicios de recopilación de información estadística de coyuntura, tanto económica como sociodemográfica. El sitio da acceso a la mayoría de la información estadística recopilada por el país. 

https://www.ine.gob.gt/ine/encuesta-nacional-de-empleo-e-ingresos/ Encuesta Nacional de Empleo e Ingresos 2021
https://www.censopoblacion.gt/censo2018/vivienda.php
https://www.ine.gob.gt/ine/poblacion-menu/ Censos Nacionales
https://www.ine.gob.gt/ine/estadisticas-de-migracion/ Estadísticas de migración. Enfocadas a la temática de la migración de 2013 a 2020 presentando cifras en dos documentos: I. Deportados II. Flujo migratorio que registra la Dirección General de Migración en las diferentes fronteras del país. Asimismo, e incluyen Estadísticas de Migración y Migración Laboral.


### Encuesta Nacional de Empleo e Ingreso

+ Contiene variables como PEA, Subocupados, desempleados, etc.
+ ¿Empleado de gobierno o privado?
+ Sectores en los cuales trabaja
+ Nivel educativo
+ Área de sus estudios
+ ¿Cómo buscó su empleo actual?
+ Por qué cree que está desempleado
+ Prestaciones laborales
+ Etnicidad

### Instituto Guatemalteco de Migración

Guatemala cuenta con un instituto especializado en migración que publica datos sobre este tema: el Instituto Guatemalteco de Migración. 

+ Tienen una solicitud de acceso a datos
datosmacro.expansion.com
+ Tienen estadísticas sobre emigración, pero no encuentro la fuente de sus datos. 
+ Los datos son cada 2 años

https://igm.gob.gt/category/estadisticas/

### Otros

Además, existen distintos programas, principalmente internacionales o regionales, que publican una gran cantidad de los datos sobre migración. La mayoría de los programas son gestionados por organizaciones internacionales o instituciones nacionales, particularmente de estadística. La mayoría son encuestas sobre Demografía u Hogares. En Guatemala existen los siguientes: 

+ DTM Matriz de Seguimiento de Desplazamiento

https://dtm.iom.int/guatemala

https://reliefweb.int/report/guatemala/guatemala-dtm-baseline-assessment-irregular-migration-flows-and-mobility-3


+ Iniciativa de Gestión de Información de Movilidad Humana en el Triángulo Norte

https://mic.iom.int/webntmi/guatemala-3/


